service: <%= name %>

frameworkVersion: '2'
variablesResolutionMode: 20210326

custom:
  stage: ${env:STAGE, opt:stage, 'development'}
  variables: ${file(./serverless/config/variables.${self:custom.stage}.yml)}

  webpack:
    keepOutputDirectory: true

  localstack:
    debug: true
    stages:
      - development
    autostart: false
    lambda:
      mountCode: false

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs<%= nodeVersion %>
  stage: ${self:custom.stage}
  region: ${self:custom.variables.region}
  profile: ${self:custom.variables.profile}
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 30
  stackName: ${self:custom.variables.stackName}
  stackTags: ${self:custom.variables.tags}
  deploymentBucket:
    name: ${self:custom.variables.bucketName}
    maxPreviousDeploymentArtifacts: 3
    tags: ${self:custom.variables.tags}

functions:
  example: ${file(./serverless/functions/example.yml)}
  
resources:
  - Resources: ${file(./serverless/infrastructure/iam.yml):Resources}
  - Outputs: ${file(./serverless/infrastructure/iam.yml):Outputs}
